### ISSUE TITLE
Resource should have a unique_together on name and event

### ISSUE THREAD

**Issue by luac** [learning-unlimited/ESP-Website#2036] opened 2016-02-17 06:22 UTC
This would prevent duplicate room problems such as the one that discovered #2035.

The main effort would be to write the migration that cleans up existing duplicates, which I'm not sure how to do.

**Comment by btidor** [comment] 2016-02-17 21:01
Closing as a duplicate of #303

**Closed by btidor** 2016-02-17 21:01 UTC
