### ISSUE TITLE
Resource Types Should Have Editable Interface Outside Admin Panel

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1059] opened 2014-02-19 00:43 UTC
Resources types and choices are customizable in the admin panel, but not anywhere else, so it is not clear you can do this unless you already know about that feature. This functionality should be available in the main website.

**Comment by willgearty** [comment] 2016-07-06 19:17
Beyond this, classroom furnishings should include the option to select resource choices rather than entire resource types (if a resource type has a choice, it is most probably that classrooms do not have all the choices as furnishings).

Currently, we need to add additional resource types after teacher registration closes in order to facilitate proper scheduling (manual). This process is extremely convoluted.

**Comment by benjaminjkraft** [comment] 2016-07-17 07:44
@willgearty Can you make a separate issue for that?  It would require more changes than just to the interface, and is separate from what Jordan suggested above.

**Comment by willgearty** [comment] 2016-07-17 16:52
@benjaminjkraft Done #2140.

**Comment by willgearty** [comment] 2017-05-12 18:05
Duplicate of #372

**Comment by benjaminjkraft** [comment] 2017-05-13 01:54
Yup!

**Closed by benjaminjkraft** 2017-05-13 01:54 UTC
Labels: Admin Panel, Development, Enhancement, Resources, UserInterface
