### ISSUE TITLE
Caching of "Students who attended" in dashboard (JSONDataModule.stats doesn't depend on Record)

### ISSUE THREAD

**Issue by pteromys** [learning-unlimited/ESP-Website#1684] opened 2015-05-02 16:11 UTC
UChicago admins had a little moment of sadness when the dashboard claimed only 13 students had checked in. Turns out there were 30 at the time, but `JSONDataModule.stats` doesn't update when new `Record`s are created.

To make it less expensive to calculate, we could cache functions like `StudentRegCore.students` and set them up in a tree of `depend_on_cache`s.

**Comment by mgersh** [comment] 2015-05-02 18:32
Duplicate of lots of things. Keeping #827 and closing the rest.

**Closed by mgersh** 2015-05-02 18:32 UTC
Labels: Caching, Feature Request
