### ISSUE TITLE
Room schedules should be sorted by room number

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#2377] opened 2017-04-23 15:17 UTC
Room schedules should be sorted by room number, so that all the schedules in one building are together.

Requested by Stanford Splash.

**Comment by hwatheod** [comment] 2017-04-23 15:21
I noticed in the code in programprintables.py that it's currently sorted by starting time block. Is there some reason for doing it this way? This only seems to make sense if you were putting all the 10:00 signs up right before 10:00, etc., but this doesn't seem very efficient.

**Comment by benjaminjkraft** [comment] 2017-04-23 16:24
Dupe of #1531.  I agree that doesn't make much sense and we should just change it.

**Closed by benjaminjkraft** 2017-04-23 16:24 UTC
Labels: ChapterRequest, Easy, Printables
