### ISSUE TITLE
Unicode error in volunteer CSV if volunteer name has non-ASCII characters

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2300] opened 2017-01-22 21:47 UTC
See https://sentry.mit.edu/esp/esp-website/issues/278/; here's the traceback:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1: ordinal not in range(128)
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "esp/web/views/main.py", line 101, in program
    newResponse = ProgramModuleObj.findModule(request, tl, one, two, module, extra, prog)
  File "esp/program/modules/base.py", line 205, in findModule
    return getattr(moduleobj, call_txt)(request, tl, one, two, call_txt, extra, prog)
  File "esp/program/modules/base.py", line 425, in _checkAdmin
    return method(moduleObj, request, *args, **kwargs)
  File "esp/program/modules/handlers/volunteermanage.py", line 72, in volunteering
    write_csv.writerow((request.timeslot.description, request.timeslot.pretty_time(), offer.name, offer.phone, offer.email))
```

**Comment by jerrywu64** [comment] 2017-03-07 05:55
Duplicate of #1893.

**Closed by jerrywu64** 2017-03-07 05:55 UTC
