### ISSUE TITLE
Schedule Generator cannot Handle Fancy Characters

### ISSUE THREAD

**Issue by bhorowitz** [learning-unlimited/ESP-Website#2362] opened 2017-03-30 17:17 UTC
If a username, firstname, or lastname has a smiley face (or other non-ascii character) the schedule generator to create a tex or pdf schedule will not work and cause a site error. We should probably just filter out all such non-standard characters.

**Comment by benjaminjkraft** [comment] 2017-07-09 19:52
Dupe of #620.

**Closed by benjaminjkraft** 2017-07-09 19:52 UTC
