### ISSUE TITLE
Onsite grid makes the site sad

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#815] opened 2013-11-23 14:58 UTC
The class changes grid generates a lot of load for the site, to the point where having a bunch of them open makes the server unresponsive.  We should look at both optimizing the backend and maybe making the frontend hammer things less frequently.

**Comment by luac** [comment] 2015-03-06 17:35
Closing, duplicate of #75 (and I suspect that most of what was causing the sadness was fixed in #1201).

**Closed by luac** 2015-03-06 17:35 UTC
Labels: Caching, Onsite, Performance
