### ISSUE TITLE
"Students who have attended [program]" count not updated

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1341] opened 2014-10-04 14:55 UTC
The one on the dashboard.  I'm not sure what it's counting, but the count doesn't appear to be updating, and flushing the cache didn't help.  (I noticed this on the Chicago Splash, for the Splash Fall 2014 program.)

**Comment by mgersh** [comment] 2015-05-02 18:33
Duplicate of lots of things. Keeping #827 and closing the rest.

**Closed by mgersh** 2015-05-02 18:33 UTC
Labels: Caching, Error
