### ISSUE TITLE
Cancel registration button doesn't work

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2099] opened 2016-04-10 04:26 UTC
UCSD says the cancel registration button in studentreg doesn't do anything.  Will probably require some investigation to see if that's actually the case, and if so what the issue is.

**Comment by benjaminjkraft** [comment] 2016-04-10 04:31
@mgersh says this might just be unintuitive default behavior, in which case the issue can be that it should remove students from classes by default, since that's what people will expect it to do.

**Comment by willgearty** [comment] 2017-05-13 17:45
What is the actual default behavior for the cancel registration button? I thought the default behavior was to remove students from all of their classes?

**Comment by willgearty** [comment] 2018-08-28 16:46
@benjaminjkraft bump

**Comment by benjaminjkraft** [comment] 2018-08-28 18:06
I have no idea!  I think this will take some digging in the code to see what it does, and what settings that depends on.

**Comment by willgearty** [comment] 2018-08-29 22:01
OK, looks like the cancel registration button will be [displayed](https://github.com/learning-unlimited/ESP-Website/blob/9147b7912921642812fa3fc4bfdbca35eaac9665/esp/templates/program/modules/studentregcore/mainpage.html#L122) anytime the student has a `reg_confirmed` record OR `cancel_button_dereg` is checked in the `scrmi`.

If the button is clicked, it [deletes](https://github.com/learning-unlimited/ESP-Website/blob/9147b7912921642812fa3fc4bfdbca35eaac9665/esp/esp/program/modules/handlers/studentregcore.py#L224) any `reg_confirmed` records for that student and then, if `cancel_button_dereg` is checked in the `scrmi`, it [removes](https://github.com/learning-unlimited/ESP-Website/blob/9147b7912921642812fa3fc4bfdbca35eaac9665/esp/esp/program/modules/handlers/studentregcore.py#L229) the student from their classes.

So, my best guess is that UCSD doesn't have `cancel_button_dereg` checked in the `scrmi`, so it's not removing the students from their classes?

But as far as I can tell, the button is set to work the way we want it to.

**Comment by benjaminjkraft** [comment] 2018-09-09 19:44
I see -- so perhaps the problem here is just that the default behavior is surprising, and everyone wants the `cancel_button_dereg` behavior?  I'm all in favor of removing options that no one should want, although we may want to check with e.g. @milescalabresi if he knows whether some chapters do like it this way.

**Comment by willgearty** [comment] 2018-09-10 18:07
Hmm...so one button would "unconfirm" the student and one button would actually remove them from their classes? And the presence of the second button could be set by the preexisting `cancel_button_dereg` option?

I'd agree that in that case, it should be made clearer to the students what "confirm reg" means. I think of it more as a "I'm finished registering" thing, rather than a "I'll definitely be there" thing, but it's obvious that isn't universal for admins or students. Do most programs use the customized receipts that are sent when the student clicks the "confirm reg" button?

**Comment by willgearty** [comment] 2018-09-10 18:10
Another option is to implement the "Cancel Block" buttons suggested by #2466. Then just have the "Cancel Registration" button at the bottom only perform the "unconfirm" function. Or maybe it would then be "Unconfirm Registration"?

**Comment by milescalabresi** [comment] 2018-09-10 23:11
I think most do not use those customized receipts. I agree with using a different word to distinguish the two possible meanings of "cancel." I realize not everyone treats it as a commitment, but I think that using "confirm" to mean "I'm finished" is a little pointless.

**Comment by willgearty** [comment] 2018-09-21 01:18
Wait, as long as the proper deadlines are still open, I believe students can still edit their classes even if they have clicked the "Confirm Reg" button (which is also perhaps unintuitive).

**Comment by milescalabresi** [comment] 2018-09-21 01:50
Is that true? My bad if so. Might be good to test to be sure. But yes that would be unintuitive (and perhaps change?)

**Comment by willgearty** [comment] 2020-05-03 16:26
Has anyone in this thread thought anymore about this? @kkbrum and @nrjean might have feelings as well.

**Comment by willgearty** [comment] 2020-11-13 01:12
Closing for now. The button appears to do what it is supposed to do (as opposed to the implication of this issue's title), but perhaps there are other buttons we want. New issues can be created if someone has a concrete idea of what they want for additional buttons/functionality.

**Closed by willgearty** 2020-11-13 01:12 UTC
Labels: ChapterRequest, Error, Idea for Discussion, Student Registration
