### ISSUE TITLE
if user is not logged in on webapp, show "please log in again" instead of "not checked in yet"

### ISSUE THREAD

**Issue by hwatheod** [learning-unlimited/ESP-Website#2647] opened 2018-12-02 18:36 UTC
On the webapp, right now if a student tries to change classes but they've been logged out somehow, the error message still says "not checked in yet" which is confusing. It should say a message like "please log in again" instead.

**Comment by willgearty** [comment] 2019-01-06 15:39
@hwatheod Would you be able to give more context for this so I can try to figure out what needs to be fixed in the code? Was the student on the schedule page or one of the timeslot class change pages? And was the message an actual error message page or just a popup?

**Comment by hwatheod** [comment] 2019-01-06 21:42
The student was on the schedule page (showing the complete schedule).  When he clicked on a class to change it, it popped up with "not checked in yet" (it didn't switch to an error page -- it stayed on the schedule page).  When I asked the student to click refresh on the browser, it went to the login page, which suggests that he had been logged out of his account.

**Comment by willgearty** [comment] 2019-01-06 22:05
Hmm...if a student has been logged out, shouldn't the permission decorators prevent them from reaching the schedule page, serving them the login page redirect instead?

Also, that popup should only be there if the student is truly not checked in. Actually, it could also be active if there isn't any user information, but if that's the case, then they probably wouldn't have seen anything on the schedule page to begin with...

**Comment by hwatheod** [comment] 2019-01-06 22:10
It could be that the student got to the schedule page while they were logged in, and then somehow they got logged out without leaving that schedule page. The only things I can think of are: (1) the student logged out from a different tab; or (2) the login cookie expired - how long are our cookies set for? Also, it's possible that a browser may allow you to override the cookie expiration date to be shorter.

**Comment by hwatheod** [comment] 2019-01-06 22:17
On that last sentence above, I checked Firefox and Chrome and they only have the option to clear all cookies upon exit - so probably that's not what happened.

**Comment by willgearty** [comment] 2019-01-06 22:30
But whether or not the popup is active is determined by a template context variable for whether the student is checked in or not, which is determined at the same time as the rest of the schedule information (username, enrolled classes), before loading the page. I don't believe any of it is cached, so I'm totally baffled by how anything related to logins could cause this.

**Comment by hwatheod** [comment] 2019-01-06 23:01
I just tried to reproduce hypothesis (1) above. I logged in as a student, opened 2 tabs to the website, went to the webapp in one of them. Then I logged out in the other tab, then clicked on "+" to add a class. It sent me to a login page instead of giving the popup. So that's not it.

If the "checked in" variable is determined at the time the page is loaded, is it possible that the student loaded the schedule page on their phone before they checked in, and then never refreshed the page after they checked in?  Maybe the whole login issue is a red herring.

**Comment by willgearty** [comment] 2019-01-07 02:08
That's definitely possible, and if it was a while before they checked the page again, that would explain why both a) it logged them out, and b) they were now checked in after refreshing and logging in.

I'm going to go ahead and close this because it doesn't seem like we're able to reproduce the problem, and the most likely situation is that everything was actually working properly.

**Closed by willgearty** 2019-01-07 02:08 UTC
Labels: Webapp
