### ISSUE TITLE
"class full" and "section full" errors in the catalog are strange

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#1461] opened 2014-11-06 03:08 UTC
The "class full" error is light red and says "Class temporarily full; please check back later".  The error when the section is full, but others have space says the same text, but in bright red.  It should probably give a more useful message (e.g. "Section full, check other sections of this class") and be in the same color.

**Comment by luac** [comment] 2016-02-06 20:16
Is this a duplicate of #446?

**Comment by luac** [comment] 2016-02-06 20:18
Actually, that doesn't make sense, because it was fixed in #447 which is before this ticket was filed..

**Comment by benjaminjkraft** [comment] 2016-02-06 20:22
I think it might be, and #447 may have been only a partial fix?  IIRC this one is just the display issue, it's not preventing anyone from doing anything, but it also applies to non-onsite users.

**Comment by willgearty** [comment] 2019-11-19 14:27
There was something similar implemented in https://github.com/learning-unlimited/ESP-Website/pull/2798:
https://github.com/learning-unlimited/ESP-Website/blob/2b30a013d546082780fd1f96eb31f48faf33f13b/esp/esp/program/models/class_.py#L861-L866
so we should just add another if statement or two to catch the other cases.

**Closed** 2019-12-08 00:14 UTC
Labels: Easy, Enhancement, Student Registration
