### ISSUE TITLE
Check teacher availability by block partitions, not total hours

### ISSUE THREAD

**Issue by milescalabresi** [learning-unlimited/ESP-Website#2536] opened 2018-04-02 15:31 UTC
Princeton ran into a small issue where teachers registered two sections of a three-hour class. The program is six hours long, but split into a two-hour block and a four-hour block by lunch. Consequently, the teachers weren't able to teach both sections and the program was short one class. An additional teacher reg check might prevent this in the future.

**Comment by hwatheod** [comment] 2018-04-02 15:43
Just to make sure I understand this correctly, you're saying that the issue should have been caught at class registration time (i.e. we should disallow registering two 3-hour sections in your example), rather than discovering the problem later when trying to schedule classes.

**Comment by milescalabresi** [comment] 2018-04-02 16:15
Correct. In the same way that it won't let you register 3 sections of a class if you've only marked yourself as available for 2 hours, it should not have let them register a second section of this class because there was only one stretch of time that was long enough to accommodate a section (assuming they were available for at least 3 hours during that stretch).

**Comment by willgearty** [comment] 2018-08-28 16:27
Duplicate of #106 (sadly, this problem has been around since 2011).

**Closed by willgearty** 2018-08-28 16:27 UTC
Labels: AJAX Scheduler, Enhancement, Teacher Registration
