### ISSUE TITLE
Account creation text should not be MIT ESP-specific

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#2100] opened 2016-04-10 05:45 UTC
The text is editable, but it's rather difficult to edit: you have to be logged out to see it, so you can only edit it through the admin panel (edit: or by manually looking up and going to the QSD's URL).  So we should make sure it's not MIT ESP specific, which it currently is (a mailman link, and a reference to Boston area programs).

**Comment by mgersh** [comment] 2016-04-10 18:13
Duplicate of #1679

**Closed by mgersh** 2016-04-10 18:13 UTC
Labels: Easy, Small, Starter
