### ISSUE TITLE
Argcache over-invalidating

### ISSUE THREAD

**Issue by benjaminjkraft** [learning-unlimited/ESP-Website#866] opened 2013-12-23 04:17 UTC
Run the following in a shell_plus --print-sql (with a cleared cache):

```
u1=ESPUser.objects.get(username='benkraft')
u2=ESPUser.objects.get(username='lua')
Tag.setTag("test",target=u1,value="foo")
Tag.setTag("test",target=u2,value="bar")
Tag.getTag("test",target=u1) #runs a query as expected
Tag.getTag("test",target=u1) #does not run a query as expected
Tag.getTag("test",target=u2) #runs a query as expected
Tag.getTag("test",target=u2) #does not run a query as expected
Tag.setTag("test",target=u1,value="baz")
Tag.getTag("test",target=u1) #runs a query as expected
Tag.getTag("test",target=u2) #runs a query that should be unnecessary
```

I'm fairly although not completely sure that this is not an issue with the application of argcache to tags, but rather an argcache bug.  ~~My guess is that what it's doing is seeing that a tag with one correct argument was updated, and expiring the cache, even though the other argument was not correct; that is, that when the tag with `name="test"` and `target=u1` is updated, it expires all tags with `name="test"` *or* `target=u1`, where it should be using an and, but I'm not entirely sure.  If that is in fact the bug, I claim it is a bug, since the other behavior can be accomplished by simply putting two `depend_on_row`s, but we should be careful changing it since it's possible existing code depends on it as such.~~

~~(If we do think this is a bug we want to fix, something equivalent should probably get added to the argcache tests.)~~

Looks like it happens with any cached function where the depend_on_row references some, but not all, of the arguments -- it will expire way more caches than it should. See the test test_depend_on_row_with_dummy in argcache's tests (currently in branch argcache-tests, #838).

**Comment by luac** [comment] 2015-11-14 03:40
I'm declaring this not a bug and/or see luac/django-argcache#1. Closing.

**Closed by luac** 2015-11-14 03:40 UTC
Labels: Caching
