### ISSUE TITLE
Ajaxscheduling Room Filter

### ISSUE THREAD

**Issue by jmoldow** [learning-unlimited/ESP-Website#1052] opened 2014-02-17 19:03 UTC
Pull request #199 introduced a room filter / sorter in the scheduling module. However, this feature was not included in the recent UI upgrade. We should add it back.

**Comment by mgersh** [comment] 2015-01-28 22:15
#1408 is a duplicate of this. Closing this version since there's slightly more information over there.

**Closed by mgersh** 2015-01-28 22:15 UTC
Labels: AJAX Scheduler, Enhancement, Feature Request, Resources, UserInterface
